### ISSUE TITLE
 Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.albiononline.AlbionOnline#18]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.
![captura de tela de 2018-02-03 20-59-30](https://user-images.githubusercontent.com/26097419/35773040-281a108c-092e-11e8-8ee2-2e30fd370178.png)

**Comment by LeandroStanger** [comment]
@nedrichards  could help

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.RAYxqoGHZTFe2VyiwtcQ6QHaEK%26pid%3D15.1&f=1

https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww11.onrpg.com%2Fwp-content%2Fuploads%2F2017%2F07%2FAlbion-Online-Launch.jpg&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.7UZskR2UKf1EUPBr8sIY8wHaEK%26pid%3D15.1&f=1

https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.gamingcypher.com%2Fwp-content%2Fuploads%2F2016%2F11%2FAlbion-Online-Faye-Update-Gaming-Cypher.jpg&f=1

https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fgameranx.com%2Fwp-content%2Fuploads%2F2016%2F07%2FAlbionOnlineFeatured.png&f=1

**Comment by nedrichards** [comment]
There are screenshots available in the appdata. https://github.com/flathub/com.albiononline.AlbionOnline/blob/master/com.albiononline.AlbionOnline.appdata.xml#L15
