### ISSUE TITLE
Application closes after 3%

### ISSUE THREAD

**Issue by ZeroPointEnergy** [flathub/com.albiononline.AlbionOnline#19]
- Installation works
- Launcher starts and downloads the game
- Game starts and shows the intro video, sound works as well
- On the following loading screen it crashes after reaching 3%

The following output is found in the player.log:

> [AVProVideo] Initialising AVPro Video (script v1.7.5 plugin v0.0.0) on GeForce GTX TITAN X/PCIe/SSE2/OpenGL 4.5.0 NVIDIA 396.45 (MT True) on LinuxPlayer
requesting resize 1920 x 1200
resizing window to 1920 x 1200
Desktop is 3840 x 2160 @ 30 Hz
WwiseUnity: Initialize sound engine ...
WwiseUnity: Sound engine initialized.
requesting resize 1920 x 1200
resizing window to 1920 x 1200
Desktop is 3840 x 2160 @ 30 Hz
Receiving unhandled NULL exception
#0  0x007fdf8ef34b00 in funlockfile

Any ideas?

Was running the game directly on Gentoo until they broke it with the last update from what I can tell. The guy on the forum told me Gentoo is not supported so I thought why not use flatpak then :-)

**Comment by valentindavid** [comment]
Are other flatpak games working? Is PulseAudio working, do you have sound (3% issues are usually sound related)? Maybe another thing to test is having a refresh rate of 60Hz.

**Comment by ZeroPointEnergy** [comment]
Yes, as mentioned the intro video is playing with sound. Can try to test with a different refresh rate, but I'm curious why you think that may be the issue.

**Comment by valentindavid** [comment]
The starting video uses a different engine I think. I have already seen the video playing with sound and then the initialization crashing at 3% because of sound issues.

The game is still working for me.

**Comment by valentindavid** [comment]
Has the game worked for you before and have you updated nvidia drivers? If so, try to clean-up shaders within `.var/app/com.albiononline.AlbionOnline` (not sure the path for nvidia drivers).

**Comment by ZeroPointEnergy** [comment]
I did not use it with flatpak before but I had it running directly, before they crippled the bundled libraries. Was trying to run it with flatpak because it looked like that might solve the library issues but looks like that brings just another host of issues. Sorry for bothering you, but I don't think this is the solution I was looking for. I will close this for now.
