### ISSUE TITLE
Dead Link  404: Not Found

### ISSUE THREAD

**Issue by boysssss** [flathub/com.albiononline.AlbionOnline#31]
flatpak install flathub com.albiononline.AlbionOnline

Error: While downloading https://live.albiononline.com/autoupdate/launcher-linux-setup-1.0.34.225: Server returned status 404: Not Found
error: Failed to install com.albiononline.AlbionOnline: While downloading https://live.albiononline.com/autoupdate/launcher-linux-setup-1.0.34.225: Server returned status 404: Not Found

**Comment by valentindavid** [comment]
Note that it will take some time before it is published. You can install manually a build, see the command in the pull request.

**Comment by boysssss** [comment]
I can wait. How much time does it usually take?

**Comment by valentindavid** [comment]
6 hours I think.

**Comment by boysssss** [comment]
That's pretty fast. I was thinking a day or two :D
