### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by CodeMichael** [flathub/com.albiononline.AlbionOnline#4]
```
flatpak --user install flathub com.albiononline.AlbionOnline  
Installing: com.albiononline.AlbionOnline/x86_64/stable from flathub  
[                    ] Downloading metadata: 0/(estimating) 69.7 MB (6.3 MB/s)  
error: Wrong size for extra data https://live.albiononline.com/clients/20170616104311/albion-online-setup
```
seems the installer updated.

**Comment by TingPing** [comment]
On a related note a few projects on flathub have changing installers like this, so if anybody wants to write a simple bot to monitor these that would be great.

**Comment by valentindavid** [comment]
I did not see this ticket. But I have fixed it today. Can you confirm it now works for you?

**Comment by CodeMichael** [comment]
I just re-ran it, and it ran without error.
