### ISSUE TITLE
Missing shared library

### ISSUE THREAD

**Issue by silvernode** [flathub/com.albiononline.AlbionOnline#42]
This happens on OpenSuse TumbleWeed on 2 different machines with all xdg portals installed and flatpak working with everything but Albion. The flatpak fails to launch on a fresh install and a previously working install.

`/home/mollusk/.albiononline/launcher/Albion-Online: error while loading shared libraries: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory`

I would like to know if other users have this issue as well, I have seen recent reviews on Discover (KDE App center) claiming the flatpak of Albion will not launch.

**Comment by andrelbc** [comment]
This is happening to me as well. I think it has something to do with the new albion update.

Some time ago I had this same issue and the next day it was back to normal.

**Comment by silvernode** [comment]
Flathub had an update now and the Launcher works just fine. I'll close this issue once @andrelbc confirms theirs is working as well.

**Comment by andrelbc** [comment]
The launcher is opening now, but it gives me an error saying that my disk does not have free space to download the patch.

**Comment by lumingzh** [comment]
@silvernode @andrelbc Missing sdl shared library, and will indicate disk space is not enough.

**Comment by silvernode** [comment]
All is well over here and seemingly with others in this thread. Considering this issue resolved.
