### ISSUE TITLE
Albion install not working :(

### ISSUE THREAD

**Issue by millimol-2022** [flathub/com.albiononline.AlbionOnline#45]
I’ve tried multiple times to install Albion online on my Chromebook through Linux and I always get a failure and the 7th stage of installing the game through Flathub. I’m not sure if there is an issue because the application needs an update or if it’s something wrong with my laptop. Any help would be greatly appreciated! <3

![image](https://user-images.githubusercontent.com/107880426/174653208-09b91161-13cc-49e0-97e4-e10f1077241a.png)

**Comment by millimol-2022** [comment]
I apologize for my lack of knowledge of these things. I wish it would be as simple as installing it through the play store, but my laptop isn't compatible for some reason.

**Comment by valentindavid** [comment]
I have updated the launcher. Can you try again?

**Comment by millimol-2022** [comment]
Looks like it's working fine now. Thank you so much! :D
