### ISSUE TITLE
Launcher cannot install game files

### ISSUE THREAD

**Issue by dhollinger** [flathub/com.albiononline.AlbionOnline#47]
The initial download of the game files after the launcher installation keeps failing with "failed to write <somefile>.bin"

Example:
![image](https://user-images.githubusercontent.com/2914211/175106620-d070a2c7-053b-48ae-b287-3c0ac600b9f1.png)

Tried rebooting and reinstalling

**Comment by valentindavid** [comment]
Are you sure you have enough disk space?

**Comment by dhollinger** [comment]
I have 47GB available on the partition its installed to, so yes.

**Comment by dhollinger** [comment]
Looks like it may be an issue on their end as the non-flatpak launcher was having the same issue and it's now working
