### ISSUE TITLE
Can't update the launcher

### ISSUE THREAD

**Issue by AndrzejRoskowicz** [flathub/com.albiononline.AlbionOnline#6]
New version of the launcher is released and I can't update it the typical way. 
It tells me that it's unpacking something but then it's the same version and it's wants me me to update again.

**Comment by valentindavid** [comment]
You cannot update the launcher that way. You have to update through `flatpak update`. Launcher has been updated with a4d43c1.

**Comment by AndrzejRoskowicz** [comment]
OK, but every time the new launcher is released (and it's quite often) link has to be updated manually. Can't it be automated somehow? 
If the launcher isn't updated you can't hit the "play button". 
Changing the number in version.txt after launcher is started, and switching to staging and back does the trick, but user should be able to update it without the delays.
