### ISSUE TITLE
Unable to install from flathub

### ISSUE THREAD

**Issue by Equivocal90** [flathub/com.albiononline.AlbionOnline#7]
Running the following command.
    `flatpak install --user flathub com.albiononline.AlbionOnline`
Results in the following error.
    `error: Wrong size for extra data https://live.albiononline.com/clients/20170713161744/albion-online-setup`

It appears that a file was changed as the checksum and length for `albion-online-setup` can be modified in the `com.albiononline.AlbionOnline.json` which results in success from a local repo.

**Comment by valentindavid** [comment]
Thanks. They often change the launcher these days. Should be fixed by a4d43c1.
